/*
============================================================
 SPACE DEBRIS TRACKER
 AI COLLISION PREDICTION ENGINE
============================================================

Phase 3.1

Purpose:
    Predict collision-risk severity from the orbital
    close-approach features generated by collisionService.js.

IMPORTANT:
    This is a predictive risk-ranking model.

    It is NOT an authoritative collision probability
    calculation because TLE/SGP4 data does not contain
    covariance/uncertainty information.

Inputs:
    - Miss distance
    - Relative velocity
    - Time to closest approach
    - Existing orbital risk score
    - Existing orbital risk level

Output:
    - AI prediction score
    - AI risk level
    - Confidence
    - Contributing factors
============================================================
*/


/*
============================================================
 CONFIGURATION
============================================================
*/

const MAX_SCORE = 100;


/*
============================================================
 UTILITY
============================================================
*/

function clamp(
  value,
  min,
  max
) {
  return Math.min(
    Math.max(
      value,
      min
    ),
    max
  );
}


/*
============================================================
 DISTANCE FEATURE
============================================================

Smaller miss distance = higher risk.

< 1 km      → extremely high
1–5 km       → very high
5–25 km      → high
25–50 km     → moderate
50–100 km    → lower
> 100 km     → very low
============================================================
*/

function distanceRisk(
  distanceKm
) {

  if (
    !Number.isFinite(
      distanceKm
    )
  ) {
    return 0;
  }

  if (
    distanceKm <= 1
  ) {
    return 100;
  }

  if (
    distanceKm <= 5
  ) {
    return 95;
  }

  if (
    distanceKm <= 25
  ) {
    return 85;
  }

  if (
    distanceKm <= 50
  ) {
    return 60;
  }

  if (
    distanceKm <= 100
  ) {
    return 30;
  }

  return 5;
}


/*
============================================================
 RELATIVE VELOCITY FEATURE
============================================================

Higher relative velocity means a potentially more severe
encounter.

Typical orbital relative velocities can be several km/s.

This feature is intentionally capped so an abnormal value
does not dominate the model.
============================================================
*/

function velocityRisk(
  relativeVelocityKms
) {

  if (
    !Number.isFinite(
      relativeVelocityKms
    )
  ) {
    return 0;
  }

  const normalized =
    (
      relativeVelocityKms /
      15
    ) * 100;

  return clamp(
    normalized,
    0,
    100
  );
}


/*
============================================================
 TIME-TO-APPROACH FEATURE
============================================================

An event approaching soon receives a higher priority.

< 5 min
< 15 min
< 30 min
< 60 min
< 180 min
============================================================
*/

function timeRisk(
  seconds
) {

  if (
    !Number.isFinite(
      seconds
    )
  ) {
    return 0;
  }

  if (
    seconds <= 5 * 60
  ) {
    return 100;
  }

  if (
    seconds <= 15 * 60
  ) {
    return 90;
  }

  if (
    seconds <= 30 * 60
  ) {
    return 75;
  }

  if (
    seconds <= 60 * 60
  ) {
    return 55;
  }

  if (
    seconds <= 180 * 60
  ) {
    return 30;
  }

  return 10;
}


/*
============================================================
 EXISTING ORBITAL SCORE
============================================================

collisionService.js already produces a deterministic
risk score from the SGP4 close approach.

We use it as one feature rather than replacing it.
============================================================
*/

function orbitalScoreRisk(
  riskScore
) {

  if (
    !Number.isFinite(
      riskScore
    )
  ) {
    return 0;
  }

  return clamp(
    riskScore,
    0,
    100
  );
}


/*
============================================================
 AI RISK CLASSIFICATION
============================================================
*/

function classifyPrediction(
  score
) {

  if (
    score >= 85
  ) {
    return "CRITICAL";
  }

  if (
    score >= 65
  ) {
    return "HIGH";
  }

  if (
    score >= 40
  ) {
    return "MEDIUM";
  }

  return "LOW";
}


/*
============================================================
 CONFIDENCE
============================================================

This is model confidence in the RISK RANKING, not a
real-world probability of collision.

Confidence increases when the important input features
are available.
============================================================
*/

function calculateConfidence(
  approach
) {

  let available = 0;

  let total = 4;

  if (
    Number.isFinite(
      approach.missDistanceKm
    )
  ) {
    available++;
  }

  if (
    Number.isFinite(
      approach.relativeVelocityKms
    )
  ) {
    available++;
  }

  if (
    Number.isFinite(
      approach.timeToClosestApproachSeconds
    )
  ) {
    available++;
  }

  if (
    Number.isFinite(
      approach.riskScore
    )
  ) {
    available++;
  }

  return Math.round(
    (
      available /
      total
    ) * 100
  );
}


/*
============================================================
 EXPLANATION
============================================================
*/

function generateFactors(
  approach
) {

  const factors = [];


  if (
    Number.isFinite(
      approach.missDistanceKm
    )
  ) {

    if (
      approach.missDistanceKm <= 5
    ) {

      factors.push(
        "Very small predicted miss distance"
      );

    } else if (
      approach.missDistanceKm <= 25
    ) {

      factors.push(
        "Small predicted miss distance"
      );
    }
  }


  if (
    Number.isFinite(
      approach.relativeVelocityKms
    )
  ) {

    if (
      approach.relativeVelocityKms >= 10
    ) {

      factors.push(
        "High relative encounter velocity"
      );

    } else if (
      approach.relativeVelocityKms >= 5
    ) {

      factors.push(
        "Significant relative encounter velocity"
      );
    }
  }


  if (
    Number.isFinite(
      approach.timeToClosestApproachSeconds
    )
  ) {

    if (
      approach.timeToClosestApproachSeconds
      <=
      30 * 60
    ) {

      factors.push(
        "Close approach occurring soon"
      );
    }
  }


  if (
    Number.isFinite(
      approach.riskScore
    ) &&
    approach.riskScore >= 70
  ) {

    factors.push(
      "Existing orbital risk score is elevated"
    );
  }


  if (
    factors.length === 0
  ) {

    factors.push(
      "No dominant high-risk feature detected"
    );
  }


  return factors;
}


/*
============================================================
 PREDICT SINGLE EVENT
============================================================
*/

function predictCollision(
  event
) {

  if (
    !event ||
    !event.closestApproach
  ) {

    return null;
  }


  const approach =
    event.closestApproach;


  /*
  ----------------------------------------------------------
   FEATURES
  ----------------------------------------------------------
  */

  const distance =
    distanceRisk(
      approach.missDistanceKm
    );


  const velocity =
    velocityRisk(
      approach.relativeVelocityKms
    );


  const time =
    timeRisk(
      approach.timeToClosestApproachSeconds
    );


  const orbital =
    orbitalScoreRisk(
      approach.riskScore
    );


  /*
  ----------------------------------------------------------
   WEIGHTED PREDICTION MODEL
  ----------------------------------------------------------

   Distance       45%
   Relative Vel   20%
   Time           15%
   Orbital Score  20%

   Distance receives the highest weight because the
   predicted separation is the strongest feature available
   from the current SGP4 close-approach engine.
  ----------------------------------------------------------
  */

  const score =
    (
      distance * 0.45
    ) +
    (
      velocity * 0.20
    ) +
    (
      time * 0.15
    ) +
    (
      orbital * 0.20
    );


  const predictionScore =
    Math.round(
      clamp(
        score,
        0,
        MAX_SCORE
      )
    );


  const predictionLevel =
    classifyPrediction(
      predictionScore
    );


  const confidence =
    calculateConfidence(
      approach
    );


  const factors =
    generateFactors(
      approach
    );


  return {

    predictionScore,

    predictionLevel,

    confidence,

    confidenceType:
      "MODEL_INPUT_CONFIDENCE",

    factors,

    features: {

      distanceRisk:
        Math.round(
          distance
        ),

      velocityRisk:
        Math.round(
          velocity
        ),

      timeRisk:
        Math.round(
          time
        ),

      orbitalRisk:
        Math.round(
          orbital
        )

    }

  };
}


/*
============================================================
 ANALYZE COLLISION RESULTS
============================================================
*/

function analyzePredictions(
  results
) {

  if (
    !Array.isArray(
      results
    )
  ) {

    return [];
  }


  return results
    .map(
      event => {

        const prediction =
          predictCollision(
            event
          );


        if (
          !prediction
        ) {
          return null;
        }


        return {

          ...event,

          aiPrediction:
            prediction

        };

      }
    )
    .filter(
      Boolean
    )
    .sort(
      (
        a,
        b
      ) =>
        (
          b.aiPrediction
            .predictionScore
        ) -
        (
          a.aiPrediction
            .predictionScore
        )
    );
}


/*
============================================================
 SUMMARY
============================================================
*/

function createPredictionSummary(
  results
) {

  const summary = {

    total: 0,

    critical: 0,

    high: 0,

    medium: 0,

    low: 0

  };


  if (
    !Array.isArray(
      results
    )
  ) {

    return summary;
  }


  summary.total =
    results.length;


  results.forEach(
    event => {

      const level =
        event
          ?.aiPrediction
          ?.predictionLevel;


      if (
        level === "CRITICAL"
      ) {

        summary.critical++;

      } else if (
        level === "HIGH"
      ) {

        summary.high++;

      } else if (
        level === "MEDIUM"
      ) {

        summary.medium++;

      } else {

        summary.low++;
      }

    }
  );


  return summary;
}


/*
============================================================
 EXPORTS
============================================================
*/

module.exports = {

  predictCollision,

  analyzePredictions,

  createPredictionSummary

};